[pytest]
addopts = -v -s --headed
testpaths = tests

markers =
    api_user_lifecycle: בדיקת מחזור חיים תקין של משתמש ב-API
    api_user_lifecycle_negative: בדיקות קצה ושליליות למשתמש ב-API
    order: קביעת סדר הריצה של הטסטים
    login: טסטים שקשורים לתהליך ההתחברות למערכת
    forgot_password: טסטים שקשורים לשכחתי סיסמה
    registration: טסטים שקשורים לרשום משתמש חדש