[pytest]
addopts = -v -s --headed
testpaths = tests

markers =
    order: קביעת סדר הריצה של הטסטים
    login: טסטים שקשורים לתהליך ההתחברות למערכת
    forgot_password: טסטים שקשורים לשכחתי סיסמה
    registration: טסטים שקשורים לרשום משתמש חדש